packages:
  - 'examples/*'
  - 'integration-tests/*'

catalogs:
  dev:
    '@types/node': 24.0.3
    '@virtual-live-lab/eslint-config': 2.2.21
    '@virtual-live-lab/prettier-config': 2.0.19
    '@virtual-live-lab/tsconfig': 2.1.20
    eslint: 9.27.0
    eslint-plugin-unicorn: 59.0.1
    globals: 16.1.0
    prettier: 3.5.3
    typescript: 5.8.3
    typescript-eslint: 8.33.1
  test:
    '@vitest/coverage-v8': 3.1.4
    vitest: 3.1.4
  universal-middleware:
    '@universal-middleware/core': 0.4.7
    '@universal-middleware/elysia': 0.5.0
    '@universal-middleware/h3': 0.4.9
    '@universal-middleware/hattip': 0.4.8
    '@universal-middleware/hono': 0.4.10
